import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'

import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'

import { useState } from 'react'

import ananiya from '../public/dev-ed-wave.png'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [darkMode,setDarkMode]=useState(false)

  return (
    <div className={darkMode ? "dark":""}>
      <Head>
        <title>Ananiya Getinet Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900 '>
        <section className=' bg-white min-h-screen dark:bg-gray-900'>
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className=' text-xl font-burtons'>DevelopedBy </h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)} className=' cursor-pointer text-2xl'/>
              </li>
              <li><a href="#" className=' bg-gradient-to-r from-cyan-300 to-cyan-900 text-white px-4 py-2 rounded-md ml-8'>Resume</a></li>
            </ul>
          </nav>
          <div className=' text-center p-10'>
            <h2 className=' text-5xl py-2 text-teal-600 font-medium md:text-6xl'>
              Ananiya Getinet
            </h2>
            <h3 className=' text-2xl py-2 md:text-3xl'>Web and Mobile Developer.</h3>
            <p className=' text-md py-5 leading-8 text-gray-800 md:text-xl  max-w-lg mx-auto dark:text-gray-200'>I am an a vastly experianced web and mobile programmer. I have mastered multiple languages, frameworks and languages including <span className=' text-teal-500'>REACT, Next.js, Django, TailwindCss, Flutter and ReactNative</span>. If you are looking for a person experianced in any of the above areas I am your guy feel free to contact me.</p>            
          </div>
          <div className=' text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className=' relative bg-gradient-to-b from-teal-300 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={ananiya}  layout="fill" objectFit='cover'/>
          </div>
        </section>
        {/* second page */}
        <section>
          <div>
            <h3 className=' text-2xl py-1'>Services I Offer</h3>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-300'> Since the beginning of my journey as a programmer, I've <span className=' text-teal-500'>collaborated</span> with talanted people to create various on demand products for both consumer and business use.</p>
            <p className=' text-md py-2 leading-8 text-gray-800 dark:text-gray-200'> Website developing thorugh <span className=' text-teal-500'>React, Next.js and Django</span>. Mobile application development through <span className=' text-teal-500'>React Native and Flutter</span>.</p>
          </div>
          <div className=' md:flex lg:flex gap-10'>
            <div className=' text-center shadow-lg  p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} width={100} height={100} />
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className=' py-2'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className=' py-4 text-teal-600'>Design tolls I use</h4>
              <p className=' text-gray-800'>Photoshop</p>
              <p className=' text-gray-800'>Illustrator</p>
              <p className=' text-gray-800'>Figma</p>
            </div>
            <div className=' text-center shadow-lg  p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} width={100} height={100} />
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className=' py-2'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className=' py-4 text-teal-600'>Design tolls I use</h4>
              <p className=' text-gray-800'>Photoshop</p>
              <p className=' text-gray-800'>Illustrator</p>
              <p className=' text-gray-800'>Figma</p>
            </div>
            <div className=' text-center shadow-lg  p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} width={100} height={100} />
              <h3 className=' text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className=' py-2'>Creating elegant designs suited for your needs following core design theory.</p>
              <h4 className=' py-4 text-teal-600'>Design tolls I use</h4>
              <p className=' text-gray-800'>Photoshop</p>
              <p className=' text-gray-800'>Illustrator</p>
              <p className=' text-gray-800'>Figma</p>
            </div>
          </div>
        </section>
        {/* last Section */}
        <section>
          <div>
            <h3 className=' text-2xl py-1'>Portofolio</h3>
            <p className=' text-md py-2 leading-8 text-gray-800'> Since the beginning of my journey as a programmer, I've <span className=' text-teal-500'>collaborated</span> with talanted people to create various on demand products for both consumer and business use.</p>
            <p className=' text-md py-2 leading-8 text-gray-800'> Website developing thorugh <span className=' text-teal-500'>React, Next.js and Django</span>. Mobile application development through <span className=' text-teal-500'>React Native and Flutter</span>.</p>
          </div>
          <div className=' flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className=' basis-1/3 flex-1'>
              <Image src={web1} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"  />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web2} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"  />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web3} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"  />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web4} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"  />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web5} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"  />
            </div>
            <div className=' basis-1/3 flex-1'>
              <Image src={web6} className=' rounded-lg object-cover' width={'100%'} height={'100%'} layout="responsive"  />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
